language: python
cache: pip
python:
  - "2.7"
install:
  - pip install python-coveralls coverage
  - pip install -r requirements_test.txt
script:  nosetests --with-coverage
after_success:
  - coveralls --config_file .coveragerc
sudo: false
addons:
  apt:
    packages:
      - protobuf-compiler